server:
  port: 8082

spring:
  application:
    name: course-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://sqluser:I5JTzYDmlG7nkA7a@cluster0.q5c1kgr.mongodb.net/cb_auth?retryWrites=true&w=majority&appName=cdec-dev}

logging:
  level:
    in.cloudblitz.course: DEBUG
